---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  WELCOME_MSG: "Hello from ConfigMap"
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
stringData:
  API_KEY: "super-secret-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-consumer
  template:
    metadata:
      labels:
        app: demo-consumer
    spec:
      containers:
        - name: app
          image: bash:5.2
          command: ["bash", "-c", "while true; do sleep 60; done"]
          env:
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: WELCOME_MSG
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: API_KEY
          volumeMounts:
            - name: cfg
              mountPath: /etc/cm
            - name: secret-volume
              readOnly: true
              mountPath: /etc/secret
      volumes:
        - name: cfg
          configMap:
            name: demo-config
        - name: secret-volume
          secret:
            secretName: demo-secret
